version: "3.9"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - yueyingnet

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - yueyingnet

volumes:
  mongo_data:

networks:
  yueyingnet:
